### ISSUE TITLE
Randomly outgoing encryption does not work

### ISSUE THREAD

**Issue by johntiror** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#24]
Sometimes, but not always, the encryption of an outgoing message can't be decrypted. Here an example where I didn't change anything before encrypting again.

Here the content of 'a' variable ready to be decrypted:
<img width="984" alt="schermata 2018-08-16 alle 08 52 22" src="https://user-images.githubusercontent.com/3677019/44193137-30904c80-a132-11e8-907c-de34f9b4a242.png">

Here I decrypted it:
<img width="959" alt="schermata 2018-08-16 alle 08 52 40" src="https://user-images.githubusercontent.com/3677019/44193158-3ab24b00-a132-11e8-94ab-47421c3c1dd8.png">

Here I re-encrypted without changing anything: (notice that it's different from the original)
<img width="977" alt="schermata 2018-08-16 alle 08 52 49" src="https://user-images.githubusercontent.com/3677019/44193174-456ce000-a132-11e8-8b0e-d6feeab4419f.png">

Here I try to decrypt again but it gives me error:
<img width="981" alt="schermata 2018-08-16 alle 08 52 58" src="https://user-images.githubusercontent.com/3677019/44193193-51f13880-a132-11e8-9022-362b375e7304.png">

If you want I can give you privately all my keys so you can debug it.
Thanks

**Comment by romanzaikin** [comment]
@johntiror you have opened the same issue so many times. please check again. I have found the bug.

**Comment by romanzaikin** [comment]
fixed in issue #26

**Comment by johntiror** [comment]
It still doesn't work: you can try with this message:

[248, 6, 9, 91, 75, 107, 252, 1, 56, 248, 1, 248, 2, 52, 252, 72, 10, 53, 10, 27, 51, 57, 51, 51, 53, 55, 49, 48, 48, 51, 48, 48, 64, 115, 46, 119, 104, 97, 116, 115, 97, 112, 112, 46, 110, 101, 116, 16, 1, 26, 20, 51, 69, 66, 48, 68, 53, 52, 53, 55, 57, 67, 67, 57, 55, 66, 55, 67, 53, 70, 50, 18, 7, 10, 5, 104, 101, 108, 108, 111, 24, 243, 212, 224, 220, 5, 32, 1]

**Comment by thiru112** [comment]
@johntiror I also had above-mentioned problem and I had commented also

 https://github.com/romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint/issues/26#issuecomment-415299544 [ [](url) ](url)
