### ISSUE TITLE
pip install -r requirements.txt fail and don't compile

### ISSUE THREAD

**Issue by federicomartinlara1976** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#32]
The command exposed fails with the errors:

Failed building wheel for curve25519-donna
Failed building wheel for pycrypto

the two above errors return the message:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 22: ordinal not in range(128)

what I've done wrong? 

Environment: Windows 10

**Comment by romanzaikin** [comment]
I have fixed it, you can try now

**Comment by federicomartinlara1976** [comment]
The problem persists.

This is the error when building 'curve25519._curve25519' extension

UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 22: ordinal not in range(128)
